name: Publish

on:
  workflow_dispatch: {}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version:  3.3

      - name: Build
        run: gem build invoiced.gemspec

      - name: Publish gems to Rubygems
        run: gem push invoiced-*.gem
        env:
          GEM_HOST_API_KEY: ${{secrets.GEM_HOST_API_KEY}}
